spring:

   datasource:
      url: jdbc:mysql://localhost:3306/exceltest?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: Wangkailin2535
      driver-class-name: com.mysql.cj.jdbc.Driver

   mybatis:
      typeAliasesPackage: com.langsin.pojo
      mapperLocations: classpath:mappers/*.xml
   mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp

server:
   port: 8080
